// NOTE - Define basic all of keys for eventbus / pubsub feature
const EVENT_BUS_KEY = {
  UPDATE_PROVINCE_SN: 'UPDATE_PROVINCE_SN',
  IS_SHOW_ROUTER_LOADING: 'IS_SHOW_ROUTER_LOADING',
  UPDATE_LANGUAGE_KEYPATH: 'UPDATE_LANGUAGE_KEYPATH',
  UPDATE_USER_PROFILE: 'UPDATE_USER_PROFILE',
  REQUEST_SEARCH_TASK: 'REQUEST_SEARCH_TASK',
  OPEN_MODAL_DIRECT_APP: 'OPEN_MODAL_DIRECT_APP'
};

export {
  EVENT_BUS_KEY,
};
