# github_name: [bitrix24_id, "bitrix24_name"]
dang-go2joy: [14, "Dang Nguyen"]
danny-go2joy: [393, "Danny Kim"]
dat-go2joy: [291, "Dat Tran"]
du-go2joy: [417, "Du Nguyen"]
duong-go2joy: [441, "Duong Nguyen"]
Hang-go2joy: [337, "Hang Vo"]
hieu-go2joy: [280, "Hieu Huy"]
hung-go2joy: [325, "Hung Chau"]
kyle-go2joy: [301, "Kyle Seo"]
linh-go2joy: [419, "Linh Tran"]
Loi-go2joy: [293, "Loi Nguyen"]
nguyen-go2joy: [274, "Nguyen Le"]
nhan-go2joy: [455, "Nhan Tran"]
nhat-go2joy: [465, "Nhat Bui"]
phat-go2joy: [6, "Phat Chenh"]
phat-pham-go2joy: [399, "Phat Pham"]
phu-go2joy: [445, "Phu Do"]
sara-go2joy: [439, "Sara Kim"]
simon-go2joy: [1, "Simon Byun"]
thanh-go2joy: [355, "Thanh Nguyen"]
tony-go2joy: [225, "Tony Kang"]
trinh-go2joy: [8, "Trinh Trinh"]
truong-go2joy: [457, "Truong Nguyen"]
tuan-go2joy: [345, "Tuan Le"]
tuyen-go2joy: [295, "Tuyen Le"]
