// NOTE - Event bus key interface
interface EventBustInterface {
  COMPILE_JS_REQUEST: string,
  UPDATE_STATUS_JS_REQUEST: string,
  CONVERT_SCSS_REQUEST: string,
  LOAD_FILE_JS_REQUEST: string,
  LOAD_FILE_CSS_REQUEST: string,
  TURN_ON_COMPILE_PROCESS_LOADING_REQUEST: string,
  RELOAD_PAGE_REQUEST: string,
  CONFIRM_FINISH_REQUEST: string,
  SEND_COMPILE_LIST_TO_CLIENT_REQUEST: string,
};

// NOTE - Event bus key define
const EVENT_BUS_KEY: EventBustInterface = {
  COMPILE_JS_REQUEST: 'COMPILE_JS_REQUEST',
  UPDATE_STATUS_JS_REQUEST: 'UPDATE_STATUS_JS_REQUEST',
  CONVERT_SCSS_REQUEST: 'CONVERT_SCSS_REQUEST',
  LOAD_FILE_JS_REQUEST: 'LOAD_FILE_JS_REQUEST',
  LOAD_FILE_CSS_REQUEST: 'LOAD_FILE_CSS_REQUEST',
  TURN_ON_COMPILE_PROCESS_LOADING_REQUEST: 'TURN_ON_COMPILE_PROCESS_LOADING_REQUEST',
  RELOAD_PAGE_REQUEST: 'RELOAD_PAGE_REQUEST',
  CONFIRM_FINISH_REQUEST: 'CONFIRM_FINISH_REQUEST',
  SEND_COMPILE_LIST_TO_CLIENT_REQUEST: 'SEND_COMPILE_LIST_TO_CLIENT_REQUEST',
};

export {
  EVENT_BUS_KEY,
};
